### ISSUE TITLE
ImportError: No module named dotenv

### ISSUE THREAD

**Issue by EdenKupe** [algolia/docsearch-scraper#400]
Hey guys,

I saw issue #378 but there's no resolution there :) Getting the exact same error as on that issue. I have installed django-dotenv on pip3 but am unable to do so on pip ( since it's recommended to use python3 with latest versions of django ). 

Is index.py using pip3/python3 so that it can find the correct module?

Here's my pip3 freeze, as you can see django-dotenv is installed:

`
algoliasearch==1.13.0
asn1crypto==0.22.0
attrs==17.2.0
Automat==0.6.0
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
click==6.7
constantly==15.1.0
cryptography==2.0.3
cssselect==1.0.1
Django==2.1.2
django-dotenv==1.4.2
enum34==1.1.6
future==0.16.0
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.18
pycparser==2.18
python-env==1.0.0
pytz==2018.5
requests==2.18.4
six==1.11.0
urllib3==1.22
`

**Comment by s-pace** [comment]
👋@EdenKupe

The current version of our scraper does not support python 3.

You can use [pipenv](https://pipenv.readthedocs.io/en/latest/)  with [this Pipfile](https://gist.githubusercontent.com/s-pace/7d93bb40470b90cc1a946cb4b0bee914/raw/a760416913dbb554241d8c4adb330056392dcd32/Pipfile) in order to install the correct environment. Please follow these instructions:

Place the Pipfile in your `docsearch-scraper` folder (root of the scrapper)
- Install pipenv, by running the following command:
`pipenv install` 
- Activate pipenv thanks to:
`pipenv shell`
Check that you are using the right version of python thanks to:
`python --version`
> Python 2.7

Use the scraper

Let us know if you have any issue.

**Comment by EdenKupe** [comment]
Hey!

Created the virtual environment, but got the same error. Tried installing django-dotenv and still encountered the error. Screenshot attached, I've highlighted both times I tried to execute the command, before and after django.

<img width="1207" alt="moduleerror" src="https://user-images.githubusercontent.com/27225905/46396944-795b8f00-c6f9-11e8-9277-e2889e068a7d.png">

**Comment by s-pace** [comment]
👋 @EdenKupe 

Please remove `django-dotenv` and install [`python-dotenv`](https://github.com/theskumar/python-dotenv) instead.

**Comment by EdenKupe** [comment]
Nice, working well now. Note that I also had to install builtins (with `pip install future`) and requests (with `pip install requests`). Just in case you're looking to add those as dependencies :)

Thanks for your help!
